In [3]:
library(lpSolve)
Obj <- c(300,400 )
Constraints <- matrix(c(5,4,3,5,5,4,8,4), nrow = 4, byrow = TRUE)
Inequality <- c("<=","<=",">=", ">=")
Rhs <- c(200,150,100,80)

result <- lp("max", Obj, Constraints, Inequality, Rhs)

cat("Optimal solution:\n")
cat(sprintf("x1\t%.2f\n", result$solution[1]))
cat(sprintf("x2\t%.2f\n", result$solution[2]))

cat("\nOptimal objective value:\n")
cat(sprintf("Z = %.2f\n", result$objval))

Optimal solution:
x1	30.77
x2	11.54

Optimal objective value:
Z = 13846.15


In [4]:
# Load the lpSolve library
library(lpSolve)

# Objective function coefficients (cost of foods A and B)
obj <- c(4, 3)

# Constraint matrix (nutritional values)
mat <- matrix(c(200, 100,
                1, 2,
                40, 40), nrow = 3, byrow = TRUE)

# Constraint right-hand side (nutritional requirements)
rhs <- c(4000, 50, 1400)

# Set the direction of the inequalities ('>=' in this case)
dir <- rep(">=", 3)

# Solve the linear programming problem to minimize the cost
lp_solution <- lp("min", obj, mat, dir, rhs)

# Print the solution
if(lp_solution$status == 0) {
  cat("Optimal solution found:\n")
  cat("Minimum cost of the diet:", lp_solution$objval, "\n")
  cat("Units of food A =", lp_solution$solution[1], "\n")
  cat("Units of food B =", lp_solution$solution[2], "\n")
} else {
  cat("No optimal solution found\n")
}

Optimal solution found:
Minimum cost of the diet: 110 
Units of food A = 5 
Units of food B = 30 


In [5]:
# Install lpSolve package
install.packages("lpSolve")

# Load the lpSolve library
library(lpSolve)

# Objective function coefficients
obj <- c(60, 26, 15, 4.75)

# Constraint matrix
mat <- matrix(c(20, 9, 6, 1,
                10, 4, 2, 1), nrow = 2, byrow = TRUE)

# Constraint right-hand side
rhs <- c(40, 20)

# Set the direction of the inequalities ('<=' in this case)
dir <- c("<=", "<=")

# Solve the linear programming problem
lp_solution <- lp("max", obj, mat, dir, rhs, all.int = TRUE)

# Print the solution
if(lp_solution$status == 0) {
  cat("Optimal solution found:\n")
  cat("Objective value (Max Z):", lp_solution$objval, "\n")
  cat("X1 =", lp_solution$solution[1], "\n")
  cat("X2 =", lp_solution$solution[2], "\n")
  cat("X3 =", lp_solution$solution[3], "\n")
  cat("X4 =", lp_solution$solution[4], "\n")
} else {
  cat("No optimal solution found\n")
}

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done



Optimal solution found:
Objective value (Max Z): 123 
X1 = 0 
X2 = 4 
X3 = 0 
X4 = 4 


In [6]:
# Load the lpSolve library
library(lpSolve)

# Objective function coefficients
obj <- c(2, 4)

# Constraint matrix
mat <- matrix(c(1, 2,
                1, 1), nrow = 2, byrow = TRUE)

# Constraint right-hand side
rhs <- c(5, 4)

# Set the direction of the inequalities ('<=' in this case)
dir <- rep("<=", 2)

# Solve the linear programming problem
lp_solution <- lp("max", obj, mat, dir, rhs)

# Print the solution
if(lp_solution$status == 0) {
  cat("Optimal solution found:\n")
  cat("Objective value (Max Z):", lp_solution$objval, "\n")
  cat("X1 =", lp_solution$solution[1], "\n")
  cat("X2 =", lp_solution$solution[2], "\n")
} else {
  cat("No optimal solution found\n")
}

Optimal solution found:
Objective value (Max Z): 10 
X1 = 0 
X2 = 2.5 


In [7]:
# Load the lpSolve library
library(lpSolve)

# Objective function coefficients
obj <- c(3, 5)

# Constraint matrix
mat <- matrix(c(1, -2,
                1, 0,
                0, 1), nrow = 3, byrow = TRUE)

# Constraint right-hand side
rhs <- c(6, 10, 1)

# Set the direction of the inequalities ('<=' in this case)
dir <- rep("<=", 3)

# Solve the linear programming problem
lp_solution <- lp("max", obj, mat, dir, rhs)

# Print the solution
if(lp_solution$status == 0) {
  cat("Optimal solution found:\n")
  cat("Objective value (Max Z):", lp_solution$objval, "\n")
  cat("X1 =", lp_solution$solution[1], "\n")
  cat("X2 =", lp_solution$solution[2], "\n")
} else {
  cat("No optimal solution found\n")
}

Optimal solution found:
Objective value (Max Z): 29 
X1 = 8 
X2 = 1 


In [8]:
 #Install the lpSolve package
if (!require("lpSolve")) {
  install.packages("lpSolve")
}

# load the lpSolve package
library(lpSolve)

# Define the transportation costs matrix
cost_matrix <- matrix(c(
  6, 3, 5, 4,
  5, 9, 2, 7,
  5, 7, 8, 6
  ), nrow = 3, byrow = TRUE)

# Define the supply and demand vectors
supply <- c(22, 15, 8)
demand <- c(7, 12, 17, 9)

# Solve the transportation problem
result <- lp.transport(cost = cost_matrix, direction = "min",
                       row.signs = rep("=", nrow(cost_matrix)),
                       row.rhs = supply,
                       col.signs = rep("=", ncol(cost_matrix)),
                       col.rhs = demand)

# Display the result
cat("Optimal Transportation :\n")
print(result$solution)

cat("\nTotal Cost:\n")
cat("Z =", result$objval)

Optimal Transportation :
     [,1] [,2] [,3] [,4]
[1,]    0   12    2    8
[2,]    0    0   15    0
[3,]    7    0    0    1

Total Cost:
Z = 149

In [9]:
# Install the lpSolve package
if (!require("lpSolve")) {
  install.packages("lpSolve")
}

# load the lpSolve package
library(lpSolve)

# Define the cost matrix (or profit matrix)
cost_matrix <- matrix(c(
  15, 10, 9,
  9, 15, 10,
  10, 12, 8
), nrow = 3, byrow = TRUE)

# Solve the assignment problem
result <- lp.assign(cost_matrix)

# Display the result
cat("Optimal Assignment:\n")
print(result$solution)

cat("\nTotal Cost :\n")
cat("Z =", result$objval)
     

Optimal Assignment:
     [,1] [,2] [,3]
[1,]    0    1    0
[2,]    1    0    0
[3,]    0    0    1

Total Cost :
Z = 27

In [10]:
# Load the lpSolve library
library(lpSolve)

# Objective function coefficients
obj <- c(3, 1, 1, 1)

# Constraint matrix
mat <- matrix(c(-2, 2, 1, 0,
                3, 1, 0, 1), nrow = 2, byrow = TRUE)

# Right-hand side of constraints
rhs <- c(4, 6)

# Define the constraint types (equality)
con_types <- c("=", "=")

# Add artificial variables
mat_artificial <- cbind(mat, diag(2))
obj_artificial <- c(0, 0, 0, 0, 1, 1)  # Coefficients for artificial variables

# Solve LP problem with artificial variables using Big M method
lp <- lp("min", obj_artificial, mat_artificial, con_types, rhs, compute.sens = FALSE)

# Extract the solution
solution <- lp$solution[1:4]  # Extract X1, X2, X3, X4

# Print the solution
cat("Optimal Solution:")
cat("\nX1 =", solution[1])
cat("\nX2 =", solution[2])
cat("\nX3 =", solution[3])
cat("\nX4 =", solution[4])
cat("\nOptimal Z value =", lp$objval)  # Optimal Z value

Optimal Solution:
X1 = 1
X2 = 3
X3 = 0
X4 = 0
Optimal Z value = 0

In [11]:
# Install the lpSolve package
if (!require("lpSolve")) {
  install.packages("lpSolve")
}

# load the lpSolve package
library(lpSolve)

# Objective function coefficients
obj <- c(3, 4, 1, 7)

# Constraint matrix
mat <- matrix(c(8, 3, 4, 1, 
                2, 6, 1, 5, 
                1, 4, 5, 2), nrow = 3, byrow = TRUE)

# Inequality signs
constr_types <- c("<=", ">=")

# Right-hand side of constraints
rhs <- c(7, 3, 8)

# Solving the linear programming problem
result <- lp("max", obj, mat, constr_types, rhs)

# Display the result
cat("Optimal solution:\n")
cat(sprintf("x1\t%.2f\n", result$solution[1]))
cat(sprintf("x2\t%.2f\n", result$solution[2]))
cat(sprintf("x3\t%.2f\n", result$solution[3]))
cat(sprintf("x4\t%.2f\n", result$solution[4]))

cat("\nOptimal objective value:\n")
cat(sprintf("Z = %.2f\n", result$objval))


Warning message in rbind(const.mat, const.dir.num, const.rhs):
“number of columns of result is not a multiple of vector length (arg 2)”


Optimal solution:
x1	0.00
x2	0.00
x3	0.00
x4	4.00

Optimal objective value:
Z = 28.00


In [12]:
# Install the lpSolve package
if (!require("lpSolve")) {
  install.packages("lpSolve")
}

# load the lpSolve package
library(lpSolve)

# Define the cost matrix (or profit matrix)
cost_matrix <- matrix(c(
  0, 4, 7, 3,
  4, 0, 6, 3,
  7, 6, 0, 7,
  3, 3, 7, 0
), nrow = 4, byrow = TRUE)

# Solve the assignment problem
result <- lp.assign(cost_matrix)

# Display the result
cat("Optimal Assignment:\n")
print(result$solution)

cat("\nTotal Cost :\n")
cat("Z =", result$objval)
     

Optimal Assignment:
     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    1    0    0
[3,]    0    0    1    0
[4,]    0    0    0    1

Total Cost :
Z = 0

In [13]:
# Contractor bids
contractor_bids <- matrix(c(9, 14, 19, 15,
                            7, 17, 20, 19,
                            9, 18, 21, 18,
                            10, 12, 18, 19,
                            10, 15, 21, 16), nrow = 5, byrow = TRUE)

# Function to find the lowest cost for each road
find_lowest_cost <- function(bids) {
  lowest_cost <- rep(0, ncol(bids))
  for (i in 1:ncol(bids)) {
    lowest_cost[i] <- min(bids[, i])
  }
  return(lowest_cost)
}

# Function to find the contractor for each road based on lowest cost
find_contractors <- function(bids) {
  contractors <- rep(0, ncol(bids))
  for (i in 1:ncol(bids)) {
    contractors[i] <- which.min(bids[, i])
  }
  return(contractors)
}

# Find lowest cost for each road
lowest_cost <- find_lowest_cost(contractor_bids)
cat("Lowest cost for each road:", lowest_cost, "\n")

# Find contractors for each road based on lowest cost
contractors <- find_contractors(contractor_bids)
cat("Contractors for each road based on lowest cost:", contractors, "\n")

# Total cost for awarding work to the lowest cost contractors
total_cost <- sum(lowest_cost)
cat("Total cost for awarding work to lowest cost contractors:", total_cost, "lakhs\n")

# If supplementary grants are needed, calculate the amount
grant_amount <- 50  # Initial grant amount in lakh
total_grant_needed <- max(0, total_cost - grant_amount)
cat("Total supplementary grant needed (if any):", total_grant_needed, "lakhs\n")

# Contractor who will be unsuccessful in their bid
unsuccessful_contractor <- setdiff(1:5, contractors)
cat("Contractor(s) unsuccessful in their bid:", unsuccessful_contractor, "\n")


Lowest cost for each road: 7 12 18 15 
Contractors for each road based on lowest cost: 2 4 4 1 
Total cost for awarding work to lowest cost contractors: 52 lakhs
Total supplementary grant needed (if any): 2 lakhs
Contractor(s) unsuccessful in their bid: 3 5 


In [14]:
# Load the lpSolve library
library(lpSolve)

# Objective function coefficients
obj <- c(3, 2, 5)

# Constraint matrix
mat <- matrix(c(1, 2, 1,
                3, 0, 2,
                1, 4, 0), nrow = 3, byrow = TRUE)

# Constraint right-hand side
rhs <- c(430, 460, 420)

# Set the direction of the inequalities ('<=' in this case)
dir <- rep("<=", 3)

# Solve the linear programming problem using the Simplex method
lp_solution <- lp("max", obj, mat, dir, rhs)

# Print the solution
if(lp_solution$status == 0) {
  cat("Optimal solution found:\n")
  cat("Objective value (Max Z):", lp_solution$objval, "\n")
  cat("X1 =", lp_solution$solution[1], "\n")
  cat("X2 =", lp_solution$solution[2], "\n")
  cat("X3 =", lp_solution$solution[3], "\n")
} else {
  cat("No optimal solution found\n")
}

Optimal solution found:
Objective value (Max Z): 1350 
X1 = 0 
X2 = 100 
X3 = 230 
